openapi: 3.0.0
info:
  version: 0.0.1
  title: CMSDK Lighting control API
  description: REST API to control RGB lighting for CoolerMaster hardware

servers:
  - description: localhost server
    url: http://localhost:10007/api/v1

paths:
  /sdkversion:
    get:
      description: Gets the API Version.
      operationId: getSdkVersion
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - version
                properties:
                  version:
                    description: Version number for Coolermaster SDK
                    type: integer
                    example: 24
  /sys/peakvolume:
    get:
      description: Gets the peak volume
      operationId: getSysPeakVolume
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - peak_volume
                properties:
                  peak_volume:
                    description: Peak volume, in the range 0 - 1
                    type: number
                    example: 0.15
  /sys/ram:
    get:
      description: Gets the peak volume
      operationId: getSysRamPercentage
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - ram_percentage
                properties:
                  ram_percentage:
                    description: Ram percentage between 0 - 100
                    type: number
                    example: 35
  /devices/{device}:
    get:
      description: Get hardware information about device
      operationId: getDeviceInfo
      parameters:
        - $ref: 'paramObjects.yaml#/parameters/device'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - plugged_in
                properties:
                  plugged_in:
                    description: Whether the specified device is plugged in
                    type: boolean
                    example: true
        '500':
          $ref: './errorTypes.yaml#/errorCodes/500'
    put:
      description: Set device RGB properties
      operationId: putDeviceInfo
      parameters:
        - $ref: 'paramObjects.yaml#/parameters/device'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: >
                    Whether to enable API RGB control for specified device
                  default: false
              required:
                - enabled
      responses:
        '200':
          description: Successful
        '400':
          $ref: './errorTypes.yaml#/errorCodes/400'
        '500':
          $ref: './errorTypes.yaml#/errorCodes/500'
  /devices/{device}/color/{row}/{col}:
    put:
      description: Set individual key's RGB Color
      operationId: putDeviceColorKey
      parameters:
        - $ref: './paramObjects.yaml#/parameters/device'
        - in: path
          name: row
          required: true
          description: Row of the keyboard to set LED color
          schema:
            type: integer
            minimum: 0
            maximum: 7
            exclusiveMaximum: true
        - in: path
          name: col
          required: true
          description: Column of keybaoard to set LED color
          schema:
            type: integer
            minimum: 0
            maximum: 24
            exclusiveMaximum: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './bodyTypes.yaml#/requestTypes/RGBColor'
      responses:
        '200':
          description: Successful
        '400':
          $ref: './errorTypes.yaml#/errorCodes/400'
        '500':
          $ref: './errorTypes.yaml#/errorCodes/500'
